layout_spectrum: 0.17884
color:
  saturation: 0.3002148
  brandStrength: 1
  lightness: 0.4441461
  brandColors:
    - '#0D0A0B'
    - '#C7C5B5'
    - '#9A9B90'
    - '#5D4A5C'
    - '#FFFFFB'
  rhythmicContrast: 0.716971
typography_spectrum: 1
name: TheTarkinGroup
